package gui;

import controller.Controller;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.util.Arrays;
import java.util.Locale;

public class login {
    private final Controller controller;
    private JPanel panel;
    private JTextField textField1;
    private JPasswordField passwordField1;
    private JButton ACCEDIButton;

    public login() {
        this(new Controller());
    }

    public login(Controller controller) {
        this.controller = controller != null ? controller : new Controller();

        configureUi();
    }

    public JComponent getContentPane() {
        return panel;
    }

    private void configureUi() {
        panel.setBorder(BorderFactory.createEmptyBorder(24, 24, 24, 24));
        panel.setBackground(new Color(245, 247, 250));

        ACCEDIButton.addActionListener(e -> {
            String username = readUsername();
            if (username.isEmpty()) {
                JOptionPane.showMessageDialog(panel, "Inserisci un nome utente per procedere.", "Accesso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            char[] passwordChars = passwordField1.getPassword();
            String password = passwordChars != null ? new String(passwordChars) : "";
            if (passwordChars != null) {
                Arrays.fill(passwordChars, '\0');
            }

            if (password.isEmpty()) {
                JOptionPane.showMessageDialog(panel, "Inserisci password per procedere.", "Accesso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            var utenteLoggato = controller.effettuaLogin(username, password);
            if (utenteLoggato == null) {
                JOptionPane.showMessageDialog(panel, "Credenziali non valide.", "Accesso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Controller.RuoloUtente ruolo = controller.determinaRuolo(utenteLoggato);
            apriDashboardPer(ruolo);
            chiudiFinestraCorrente();
        });
    }

    private String readUsername() {
        return textField1.getText() != null ? textField1.getText().trim() : "";
    }

    private void chiudiFinestraCorrente() {
        Window currentWindow = SwingUtilities.getWindowAncestor(panel);
        if (currentWindow != null) {
            currentWindow.dispose();
        }
    }

    private void apriDashboardPer(Controller.RuoloUtente ruolo) {
        switch (ruolo) {
            case AMMINISTRATORE:
                apriFinestra(new gui.Amministratore(controller).getContentPane(), "Dashboard amministratore", new Dimension(860, 560));
                break;
            case MEDICO:
                apriFinestra(new gui.Medico(controller).getContentPane(), "Dashboard medico", new Dimension(980, 640));
                break;
            default:
                JOptionPane.showMessageDialog(panel, "Tipo utente non supportato.", "Accesso", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }

    private void apriFinestra(JComponent contentPane, String titolo, Dimension dimensioneMinima) {
        JFrame homeFrame = new JFrame(titolo);
        homeFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        homeFrame.setContentPane(contentPane);
        homeFrame.setMinimumSize(dimensioneMinima);
        homeFrame.setLocationRelativeTo(null);
        homeFrame.pack();
        homeFrame.setVisible(true);
    }

    public static void showLogin(Controller controller) {
        JFrame frame = new JFrame("Accedi al sistema");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        login loginView = new login(controller);
        frame.setContentPane(loginView.getContentPane());
        frame.setMinimumSize(new Dimension(420, 300));
        frame.setLocationRelativeTo(null);
        frame.pack();
        frame.setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                showLogin(null);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.setBackground(new Color(-7303024));
        panel.setEnabled(true);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Dialog", Font.BOLD, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Accedi al sistema");
        panel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Nome utente");
        panel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textField1 = new JTextField();
        panel.add(textField1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(180, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Password");
        panel.add(label3, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField1 = new JPasswordField();
        panel.add(passwordField1, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(180, -1), null, 0, false));
        ACCEDIButton = new JButton();
        ACCEDIButton.setText("ACCEDI");
        panel.add(ACCEDIButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
